# 넘파이(Numpy) DNN 구현과 활용
## 넘파이(NumPy) DNN 구현하기
### 3입력 3출력 인공 신경망 구현하기

In [2]:
import numpy as np

# numpy의 실수 출력 방법을 변경
# 소수점 이하 3자리까지 출력
np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}" .format(x)})


In [3]:
X = np.array([[2,3,4]])
T = np.array([[27,-30,179]])
W = np.array([[3,5,8], [4,6,9], [5,7,10]])
B = np.array([[1,2,3]])

for epoch in range(1000):
    print('\nepoch = %d' %epoch)
    
    Y = X @ W + B # @는 행렬의 곱
    print( 'Y = ', Y)
    
    E = np.sum((Y-T)**2/2)
    print('E = %.7f' %E)
    if E < 0.0000001:
        break
    
    Yb = Y - T
    Xb = Yb @ W.T
    Wb = X.T @ Yb
    Bb = 1 * Yb
    print(' Xb =\n', Xb)
    print(' Wb =\n', Wb)
    print(' Bb =\n', Bb)
    
    lr = 0.01
    W = W - lr * Wb
    B = B - lr * Bb
    print(' W =\n', W)
    print(' B =\n', B)



epoch = 0
Y =  [[39 58 86]]
E = 8268.5000000
 Xb =
 [[-268 -261 -254]]
 Wb =
 [[  24  176 -186]
 [  36  264 -279]
 [  48  352 -372]]
 Bb =
 [[ 12  88 -93]]
 W =
 [[ 2.760  3.240  9.860]
 [ 3.640  3.360 11.790]
 [ 4.520  3.480 13.720]]
 B =
 [[ 0.880  1.120  3.930]]

epoch = 1
Y =  [[35.400 31.600 113.900]]
E = 4051.5650000
 Xb =
 [[-419.118 -529.977 -640.836]]
 Wb =
 [[16.800 123.200 -130.200]
 [25.200 184.800 -195.300]
 [33.600 246.400 -260.400]]
 Bb =
 [[ 8.400 61.600 -65.100]]
 W =
 [[ 2.592  2.008 11.162]
 [ 3.388  1.512 13.743]
 [ 4.184  1.016 16.324]]
 B =
 [[ 0.796  0.504  4.581]]

epoch = 2
Y =  [[32.880 13.120 133.430]]
E = 1985.2668500
 Xb =
 [[-406.826 -541.150 -675.473]]
 Wb =
 [[11.760 86.240 -91.140]
 [17.640 129.360 -136.710]
 [23.520 172.480 -182.280]]
 Bb =
 [[ 5.880 43.120 -45.570]]
 W =
 [[ 2.474  1.146 12.073]
 [ 3.212  0.218 15.110]
 [ 3.949 -0.709 18.147]]
 B =
 [[ 0.737  0.073  5.037]]

epoch = 3
Y =  [[31.116  0.184 147.101]]
E = 972.7807565
 Xb =
 [[-340.366 -