# 넘파이(Numpy) DNN 구현과 활용
## 넘파이(NumPy) DNN 구현하기
### 2입력 1출력 인공 신경망 구현하기

In [2]:
import numpy as np

# numpy의 실수 출력 방법을 변경
# 소수점 이하 3자리까지 출력
np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}" .format(x)})


In [3]:
X = np.array([[2,3]])
T = np.array([[27]])
W = np.array([[3], [4]])
B = np.array([[1]])

for epoch in range(1000):
    print('\nepoch = %d' %epoch)
    
    Y = X @ W + B # @는 행렬의 곱
    print( 'Y = ', Y)
    
    E = np.sum((Y-T)**2/2)
    print('E = %.7f' %E)
    if E < 0.0000001:
        break
    
    Yb = Y - T
    Xb = Yb @ W.T
    Wb = X.T @ Yb
    Bb = 1 * Yb
    print(' Xb =\n', Xb)
    print(' Wb =\n', Wb)
    print(' Bb =\n', Bb)
    
    lr = 0.01
    W = W - lr * Wb
    B = B - lr * Bb
    print(' W =\n', W)
    print(' B =\n', B)



epoch = 0
Y =  [[19]]
E = 32.0000000
 Xb =
 [[-24 -32]]
 Wb =
 [[-16]
 [-24]]
 Bb =
 [[-8]]
 W =
 [[ 3.160]
 [ 4.240]]
 B =
 [[ 1.080]]

epoch = 1
Y =  [[20.120]]
E = 23.6672000
 Xb =
 [[-21.741 -29.171]]
 Wb =
 [[-13.760]
 [-20.640]]
 Bb =
 [[-6.880]]
 W =
 [[ 3.298]
 [ 4.446]]
 B =
 [[ 1.149]]

epoch = 2
Y =  [[21.083]]
E = 17.5042611
 Xb =
 [[-19.511 -26.308]]
 Wb =
 [[-11.834]
 [-17.750]]
 Bb =
 [[-5.917]]
 W =
 [[ 3.416]
 [ 4.624]]
 B =
 [[ 1.208]]

epoch = 3
Y =  [[21.912]]
E = 12.9461515
 Xb =
 [[-17.382 -23.528]]
 Wb =
 [[-10.177]
 [-15.265]]
 Bb =
 [[-5.088]]
 W =
 [[ 3.518]
 [ 4.777]]
 B =
 [[ 1.259]]

epoch = 4
Y =  [[22.624]]
E = 9.5749737
 Xb =
 [[-15.394 -20.903]]
 Wb =
 [[-8.752]
 [-13.128]]
 Bb =
 [[-4.376]]
 W =
 [[ 3.605]
 [ 4.908]]
 B =
 [[ 1.303]]

epoch = 5
Y =  [[23.237]]
E = 7.0816505
 Xb =
 [[-13.568 -18.470]]
 Wb =
 [[-7.527]
 [-11.290]]
 Bb =
 [[-3.763]]
 W =
 [[ 3.680]
 [ 5.021]]
 B =
 [[ 1.340]]

epoch = 6
Y =  [[23.763]]
E = 5.2375887
 Xb =
 [[-11.912 -16.