# 넘파이(Numpy) DNN 구현과 활용
## 넘파이(NumPy) DNN 구현하기
### 2입력 2은닉 2출력 인공 신경망 구현하기

In [2]:
import numpy as np

# numpy의 실수 출력 방법을 변경
# 소수점 이하 3자리까지 출력
np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}" .format(x)})


In [ ]:
I = np.array([[.05, .10]])
T = np.array([[.01, .99]])

WH = np.array([[.15,.25], [.20,.30]])
BH = np.array([[.35,.35]])

WO = np.array([[.40,.50],[.45,.55]])
BO = np.array([[.60,.60]])

for epoch in range(1000):
    print(' epoch = %d' %epoch)
    
    H = I @ WH + BH
    O = H @ WO + BO
    print(' O = \n', O)
    
    E = np.sum((O-T)**2/2)
    print('  E = %.7f' %E)
    if E <  0.0000001:
        break
    
    Ob = O - T
    Hb = Ob @ WO.T
    WHb = I.T @ Hb
    BHb = 1 * Hb
    
    WOb = H.T @ Ob
    BOb = 1 *  Ob
    print(' WHb =\n', WHb)
    print(' BHb =\n', BHb)
    print(' WOb =\n', WOb)
    print(' BOb =\n', BOb)
    
    lr = 0.01
    WH = WH - lr *  WHb
    BH = BH - lr *  BHb
    WO = WO - lr *  WOb
    BO = BO - lr *  BOb
    print(' WH =\n', WH)
    print(' BH =\n', BH)
    print(' WO =\n', WO)
    print(' BO =\n', BO)


 epoch = 0
 O = 
 [[ 0.928  1.005]]
  E = 0.4211248
 WHb =
 [[ 0.019  0.021]
 [ 0.037  0.042]]
 BHb =
 [[ 0.374  0.421]]
 WOb =
 [[ 0.346  0.006]
 [ 0.360  0.006]]
 BOb =
 [[ 0.918  0.015]]
 WH =
 [[ 0.150  0.250]
 [ 0.200  0.300]]
 BH =
 [[ 0.346  0.346]]
 WO =
 [[ 0.397  0.500]
 [ 0.446  0.550]]
 BO =
 [[ 0.591  0.600]]
 epoch = 1
 O = 
 [[ 0.912  1.000]]
  E = 0.4071442
 WHb =
 [[ 0.018  0.020]
 [ 0.036  0.041]]
 BHb =
 [[ 0.363  0.408]]
 WOb =
 [[ 0.337  0.004]
 [ 0.350  0.004]]
 BOb =
 [[ 0.902  0.010]]
 WH =
 [[ 0.150  0.250]
 [ 0.199  0.299]]
 BH =
 [[ 0.343  0.342]]
 WO =
 [[ 0.393  0.500]
 [ 0.443  0.550]]
 BO =
 [[ 0.582  0.600]]
 epoch = 2
 O = 
 [[ 0.897  0.996]]
  E = 0.3937590
 WHb =
 [[ 0.018  0.020]
 [ 0.035  0.040]]
 BHb =
 [[ 0.352  0.396]]
 WOb =
 [[ 0.328  0.002]
 [ 0.341  0.002]]
 BOb =
 [[ 0.887  0.006]]
 WH =
 [[ 0.149  0.249]
 [ 0.199  0.299]]
 BH =
 [[ 0.339  0.338]]
 WO =
 [[ 0.390  0.500]
 [ 0.439  0.550]]
 BO =
 [[ 0.573  0.600]]
 epoch = 3
 O = 
 [[ 0.883  