# 넘파이(Numpy) DNN 구현과 활용
## 넘파이(NumPy) DNN 구현하기
### 활성화 함수 적용하기
#### ReLU 함수 적용해 보기

In [4]:
import numpy as np

# numpy의 실수 출력 방법을 변경
# 소수점 이하 3자리까지 출력
np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}" .format(x)})


In [6]:
I = np.array([[.05, .10]])
T = np.array([[.01, .99]])

WH = np.array([[.15,.25], [.20,.30]])
BH = np.array([[.35,.35]])

WO = np.array([[.40,.50],[.45,.55]])
BO = np.array([[.60,.60]])

for epoch in range(10000):
    print(' epoch = %d' %epoch)
    
    H = I @ WH + BH
    H = (H>0)*H
    
    O = H @ WO + BO
    O = (O >0) *O
    print(' O = \n', O)
    
    E = np.sum((O-T)**2/2)
    print('  E = %.7f' %E)
    if E <  0.0000001:
        break
    
    Ob = O - T
    Ob  = Ob*(H>0)*1
    
    Hb = Ob @WO.T
    Hb = Hb*(H>0)*1
    
    WHb = I.T @ Hb
    BHb = 1*Hb
    WOb = H.T@Ob
    BOb = 1*Ob
    
    lr = 0.01
    WH = WH - lr * WHb
    BH = BH - lr * BHb
    WO = WO - lr * WOb
    BO = BO - lr * BOb


 epoch = 0
 O = 
 [[ 0.928  1.005]]
  E = 0.4211248
 epoch = 1
 O = 
 [[ 0.912  1.000]]
  E = 0.4071442
 epoch = 2
 O = 
 [[ 0.897  0.996]]
  E = 0.3937590
 epoch = 3
 O = 
 [[ 0.883  0.992]]
  E = 0.3809365
 epoch = 4
 O = 
 [[ 0.869  0.988]]
  E = 0.3686461
 epoch = 5
 O = 
 [[ 0.855  0.984]]
  E = 0.3568592
 epoch = 6
 O = 
 [[ 0.841  0.981]]
  E = 0.3455493
 epoch = 7
 O = 
 [[ 0.828  0.977]]
  E = 0.3346915
 epoch = 8
 O = 
 [[ 0.815  0.974]]
  E = 0.3242627
 epoch = 9
 O = 
 [[ 0.803  0.971]]
  E = 0.3142410
 epoch = 10
 O = 
 [[ 0.790  0.968]]
  E = 0.3046061
 epoch = 11
 O = 
 [[ 0.778  0.965]]
  E = 0.2953389
 epoch = 12
 O = 
 [[ 0.766  0.962]]
  E = 0.2864215
 epoch = 13
 O = 
 [[ 0.755  0.960]]
  E = 0.2778372
 epoch = 14
 O = 
 [[ 0.744  0.957]]
  E = 0.2695699
 epoch = 15
 O = 
 [[ 0.732  0.955]]
  E = 0.2616050
 epoch = 16
 O = 
 [[ 0.722  0.952]]
  E = 0.2539283
 epoch = 17
 O = 
 [[ 0.711  0.950]]
  E = 0.2465268
 epoch = 18
 O = 
 [[ 0.701  0.948]]
  E = 0.2393878
 ep