# 넘파이(Numpy) DNN 구현과 활용
## 넘파이(NumPy) DNN 구현하기
### 활성화 함수 적용하기
#### tanh 함수 적용해 보기

In [1]:
import numpy as np

# numpy의 실수 출력 방법을 변경
# 소수점 이하 3자리까지 출력
np.set_printoptions(formatter={'float_kind':lambda x: "{0:6.3f}" .format(x)})


In [ ]:
I = np.array([[.05, .10]])
T = np.array([[.01, .99]])

WH = np.array([[.15,.25], [.20,.30]])
BH = np.array([[.35,.35]])

WO = np.array([[.40,.50],[.45,.55]])
BO = np.array([[.60,.60]])

for epoch in range(10000):
    print(' epoch = %d' %epoch)
    
    H = I @ WH + BH
    H = np.tanh(H)
    
    O = H @ WO + BO
    O = np.tanh(O)
    print(' O = \n', O)
    
    E = np.sum((O-T)**2/2)
    print('  E = %.7f' %E)
    if E <  0.0000001:
        break
    
    Ob = O - T
    Ob  = Ob*(1+O)*(1-O)
    
    Hb = Ob @WO.T
    Hb = Hb*(1+H)*(1-H)
    
    WHb = I.T @ Hb
    BHb = 1*Hb
    WOb = H.T@Ob
    BOb = 1*Ob
    
    lr = 0.01
    WH = WH - lr * WHb
    BH = BH - lr * BHb
    WO = WO - lr * WOb
    BO = BO - lr * BOb


 epoch = 0
 O = 
 [[ 0.346  0.357]]
  E = 0.2566479
 epoch = 1
 O = 
 [[ 0.347  0.358]]
  E = 0.2563003
 epoch = 2
 O = 
 [[ 0.348  0.359]]
  E = 0.2559558
 epoch = 3
 O = 
 [[ 0.349  0.360]]
  E = 0.2556144
 epoch = 4
 O = 
 [[ 0.350  0.362]]
  E = 0.2552760
 epoch = 5
 O = 
 [[ 0.351  0.363]]
  E = 0.2549406
 epoch = 6
 O = 
 [[ 0.352  0.364]]
  E = 0.2546083
 epoch = 7
 O = 
 [[ 0.353  0.365]]
  E = 0.2542791
 epoch = 8
 O = 
 [[ 0.354  0.366]]
  E = 0.2539529
 epoch = 9
 O = 
 [[ 0.355  0.367]]
  E = 0.2536298
 epoch = 10
 O = 
 [[ 0.356  0.368]]
  E = 0.2533097
 epoch = 11
 O = 
 [[ 0.357  0.369]]
  E = 0.2529926
 epoch = 12
 O = 
 [[ 0.358  0.370]]
  E = 0.2526785
 epoch = 13
 O = 
 [[ 0.359  0.371]]
  E = 0.2523675
 epoch = 14
 O = 
 [[ 0.361  0.373]]
  E = 0.2520595
 epoch = 15
 O = 
 [[ 0.362  0.374]]
  E = 0.2517545
 epoch = 16
 O = 
 [[ 0.363  0.375]]
  E = 0.2514525
 epoch = 17
 O = 
 [[ 0.364  0.376]]
  E = 0.2511536
 epoch = 18
 O = 
 [[ 0.365  0.377]]
  E = 0.2508576
 ep